create table all_sessions(
	fullVisitorId	numeric,
	channelGrouping	varchar,
	time_	numeric,
	country	varchar,
	city	varchar,
	totalTransactionRevenue	numeric,
	transactions	int,
	timeOnSite	numeric,
	pageviews	int,
	sessionQualityDim	int,
	date_	date,
	visitId	numeric,
	type_	varchar,
	productRefundAmount	int,
	productQuantity	int,
	productPrice	int,
	productRevenue	int,
	productSKU	varchar,
	v2ProductName	varchar,
	v2ProductCategory	varchar,
	productVariant	varchar,
	currencyCode	varchar,
	itemQuantity	int,
	itemRevenue	int,
	transactionRevenue	numeric,
	transactionId	varchar,
	pageTitle	varchar,
	searchKeyword	varchar,
	pagePathLevel1	varchar,
	eCommerceAction_type	int,
	eCommerceAction_step	int,
	eCommerceAction_option	varchar

)