--What 
SELECT CITY,
	COUNTRY,
	v2productname,
	max(sentimentscore) AS HIGHEST_PRODUCT_RATING
FROM ANALYTICS A
JOIN ALL_SESSIONS ALS ON A.FULLVISITORID = ALS.FULLVISITORID
JOIN PRODUCTS P ON ALS.PRODUCTSKU = P.SKU
WHERE 	CITY != '(not set)'
	AND	COUNTRY != '(not set)'
GROUP BY CITY,
		COUNTRY,
		v2productname
ORDER BY HIGHEST_PRODUCT_RATING DESC
LIMIT 10;