-- Question 3: How does the total amount ordered relate to its sentiment score?

SELECT DISTINCT(SKU),
	V2PRODUCTNAME,
	SBS.TOTAL_ORDERED,
	P.SENTIMENTSCORE as Sentiment_score
FROM PRODUCTS P
JOIN SALES_BY_SKU SBS ON P.SKU = SBS.PRODUCTSKU
JOIN ALL_SESSIONS ALLS USING(PRODUCTSKU)
WHERE TOTAL_ORDERED > 0
ORDER BY TOTAL_ORDERED DESC,
	Sentiment_score DESC
LIMIT 10;