SELECT *
FROM SALES_BY_SKU;--reutrns 462 rows


SELECT DISTINCT(PRODUCTSKU),
	COUNT(PRODUCTSKU)
FROM SALES_BY_SKU
GROUP BY DISTINCT(PRODUCTSKU)
ORDER BY PRODUCTSKU ;--returns 462 rows


ALTER TABLE SALES_BY_SKU ADD PRIMARY KEY (PRODUCTSKU);--making PRODUCTSKU pk

ALTER TABLE SALES_BY_SKU RENAME COLUMN OTAL_ORDERED TO TOTAL_ORDERED;--fixing a typo