SELECT *
FROM sales_report;--reutrns 454 rows


SELECT DISTINCT(PRODUCTSKU),
	COUNT(PRODUCTSKU)
FROM sales_report
GROUP BY DISTINCT(PRODUCTSKU)
ORDER BY PRODUCTSKU ;--returns 454 rows


ALTER TABLE sales_report ADD PRIMARY KEY (PRODUCTSKU);--making PRODUCTSKU pk

